/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.minecraft.client;

class ModVR920JNI {
  public final static native long new_VR920();
  public final static native void VR920_setup(long jarg1, VR920 jarg1_);
  public final static native void VR920_shutdown(long jarg1, VR920 jarg1_);
  public final static native void VR920_update(long jarg1, VR920 jarg1_);
  public final static native void VR920_beginDraw(long jarg1, VR920 jarg1_, float jarg2, float jarg3);
  public final static native void VR920_endDraw(long jarg1, VR920 jarg1_);
  public final static native boolean VR920_shouldUpdate(long jarg1, VR920 jarg1_);
  public final static native void VR920_setTracking(long jarg1, VR920 jarg1_, boolean jarg2);
  public final static native void VR920_enableTracking(long jarg1, VR920 jarg1_);
  public final static native void VR920_disableTracking(long jarg1, VR920 jarg1_);
  public final static native void VR920_setStereo(long jarg1, VR920 jarg1_, boolean jarg2);
  public final static native void VR920_enableStereo(long jarg1, VR920 jarg1_);
  public final static native void VR920_disableStereo(long jarg1, VR920 jarg1_);
  public final static native void VR920_setFocalLength(long jarg1, VR920 jarg1_, float jarg2);
  public final static native float VR920_getFocalLength(long jarg1, VR920 jarg1_);
  public final static native void VR920_setEyeSeperation(long jarg1, VR920 jarg1_, float jarg2);
  public final static native float VR920_getEyeSeperation(long jarg1, VR920 jarg1_);
  public final static native void VR920_setLeftEye(long jarg1, VR920 jarg1_);
  public final static native void VR920_setRightEye(long jarg1, VR920 jarg1_);
  public final static native void VR920_waitLeftEye(long jarg1, VR920 jarg1_);
  public final static native void VR920_waitRightEye(long jarg1, VR920 jarg1_);
  public final static native float VR920_getPitch(long jarg1, VR920 jarg1_);
  public final static native float VR920_getYaw(long jarg1, VR920 jarg1_);
  public final static native float VR920_getRoll(long jarg1, VR920 jarg1_);
  public final static native void VR920_applyOrientation(long jarg1, VR920 jarg1_);
  public final static native void delete_VR920(long jarg1);
}
